name: Coleta de Dados
on:
    schedule:
        - cron: "0 0 */15 * *"
    workflow_dispatch:
jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Set up Python 3.10
          uses: actions/setup-python@v3
          with:
            python-version: "3.10"
        - name: Cache Python dependencies
          uses: actions/cache@v3
          with:
            path: ~/.cache/pip
            key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
            restore-keys: |
              ${{ runner.os }}-pip-
        - name: Install dependencies
          run: |
            make install
        - name: Coleta de Dados
          run: |
            python dados/rodando_coleta_dados.py
        - name: Commit files
        run: |
            git add .
            git commit -m "Update data: $(date +'%Y-%m-%d')"
            git push
      
          
