#https://docs.streamlit.io/develop/concepts/app-testing/automate-tests
name: Construindo and Push Docker Image 

on:
  schedule:
    - cron: "* * 3 * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Copia os arquivos do repo
      uses: actions/checkout@v4

    - name: Instalando o Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build and push Docker image
      run: |
        cd codigos_rodando/avaliacao_modelos/apresentacao_streamlit
        pwd
        docker build -t streamlit_predicao_selic .
        docker tag streamlit_predicao_selic jefersonsehnem/streamlit_predicao_selic:latest
        docker push jefersonsehnem/streamlit_predicao_selic:latest