# https://docs.streamlit.io/develop/concepts/app-testing/automate-tests
name: TesteStreamlit app
on:
  push:
    branches: ["main"]

  workflow_dispatch:

permissions:
  contents: read

jobs:
  app-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Copia os arquivos do repo
      uses: actions/checkout@v4

    - name: Instalando o Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Rodando test atraves do selenium
      run: |
        cd codigos_rodando/avaliacao_modelos/apresentacao_streamlit
        pip install -r requirements.txt
        python test_deploy_streamlit.py


      