name: Teste Actions
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Copia os arquivos do repo
        uses: actions/checkout@v4

      - name: Instalar o Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.1'

      - name: Instalar o pip
        run: |
          python -m ensurepip --default-pip
          python -m pip install --upgrade pip

      - name: Navegar e mostrar arquivos
        run: |
          cd Modelo_Previsao_Taxa_Selic
          ls -la
